# user in container
ARG CONTAINER_USER=user
ARG CONTAINER_GROUP=user

ARG CONTAINER_USER_ID=1000
ARG CONTAINER_GROUP_ID=1000

# set location of workspace directory
# (temporary space within container image)
ARG WORKSPACE_ROOT_DIR="/home/${CONTAINER_USER}"

# Alpine release
ARG ALPINE_RELEASE=3.24-alpine3.24-dev

# ansible CLI tools versions
ARG ANSIBLE_CLI_VERSION=v2.21.1

# cert-manager CLI version
ARG CM_CTL_CLI_VERSION=v2.5.0

# Helm version
ARG HELM_CLI_VERSION=v4.2.2

# kubectl version
ARG K9S_CLI_VERSION=v0.51.0

# kops version
ARG KOPS_CLI_VERSION=v1.36.0-beta.1

# kubectl version
ARG KUBECTL_CLI_VERSION=v1.36.2

# Kustomize version
ARG KUSTOMIZE_CLI_VERSION=5.8.1

# OpenTofu version
ARG OPENTOFU_CLI_VERSION=1.12.5

# OTC CLI version
ARG OTC_CLI_VERSION=v0.0.7

# SwarmCLI version
ARG SWARM_CLI_VERSION=v1.12.0

# Terraform version
ARG TERRAFORM_CLI_VERSION=1.16.0-alpha20260617

# Terragrunt version
ARG TERRAGRUNT_CLI_VERSION=v1.1.0-rc2

# container as builder for preparing OTC cloud tools
FROM dhi.io/alpine-base:${ALPINE_RELEASE} AS otc-tools-builder

LABEL stage="otc-tools-builder" \
      description="Alpine-based container builder for preparing OTC cloud tools" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tools" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# tar is installed explicitly: Alpine's "tar" package is GNU tar, needed for --no-anchored below
# (BusyBox's built-in tar applet does not support that long option)
RUN apk add --no-cache ca-certificates binutils curl unzip tar

# container as builder for preparing OTC cloud tools
FROM otc-tools-builder AS otc-tools-ansible-cli-builder

LABEL stage="otc-tools-ansible-cli-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool ansible" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool ansible" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH
ARG ANSIBLE_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download and install ansible tool
RUN apk add --no-cache python3 py3-pip
RUN python3 -m pip install --break-system-packages "https://github.com/ansible/ansible/archive/refs/tags/${ANSIBLE_CLI_VERSION}.tar.gz"


# container as builder for preparing OTC cloud tools
FROM otc-tools-builder AS otc-tools-cm-builder

LABEL stage="otc-tools-cm-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool cert-manager CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool cert-manager CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH
ARG CM_CTL_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download cert-manager
ADD "https://github.com/cert-manager/cmctl/releases/download/${CM_CTL_CLI_VERSION}/cmctl_linux_${TARGETARCH}" "${WORKSPACE_ROOT_DIR}/cmctl_linux_${TARGETARCH}"

# install cert-manager
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/cmctl_linux_${TARGETARCH}" "/usr/local/bin/kubectl-cert_manager"


# container as builder for preparing OTC cloud tools
FROM otc-tools-builder AS otc-tools-cnpg-builder

LABEL stage="otc-tools-cnpg-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool CNPG CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool CNPG CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# install kubectl CNPG plugin
RUN mkdir -p "/usr/local/bin/" && \
    curl -sSfL https://github.com/cloudnative-pg/cloudnative-pg/raw/main/hack/install-cnpg-plugin.sh | \
    sh -s -- -b /usr/local/bin


# container as builder for preparing OTC cloud tools
FROM otc-tools-builder AS otc-tools-helm-builder

LABEL stage="otc-tools-helm-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool HELM CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool HELM CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH
ARG HELM_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download HELM archive file
ADD "https://get.helm.sh/helm-${HELM_CLI_VERSION}-${TARGETOS}-${TARGETARCH}.tar.gz" "${WORKSPACE_ROOT_DIR}/"

# install HELM
RUN mkdir -p "/usr/local/bin/" && tar -xvf "${WORKSPACE_ROOT_DIR}/helm-${HELM_CLI_VERSION}-${TARGETOS}-${TARGETARCH}.tar.gz" -C "/usr/local/bin" --strip-components 1 --no-anchored "helm"


# container as builder for preparing OTC cloud tools
FROM otc-tools-builder AS otc-tools-k9s-builder

LABEL stage="otc-tools-k9s-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool k9s CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool k9s CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH
ARG K9S_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download k9s CLI binary file
ADD "https://github.com/derailed/k9s/releases/download/${K9S_CLI_VERSION}/k9s_Linux_${TARGETARCH}.tar.gz" "${WORKSPACE_ROOT_DIR}/"

# install k9s
RUN mkdir -p "/usr/local/bin/" && tar -xvf "${WORKSPACE_ROOT_DIR}/k9s_Linux_${TARGETARCH}.tar.gz" -C "/usr/local/bin" --no-anchored "k9s"


# container as builder for preparing kops OTC cloud tools
FROM otc-tools-builder AS otc-tools-kops-builder

LABEL stage="otc-tools-kops-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool kops CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool kops CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH
ARG KOPS_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download kubectl CLI binary file
ADD "https://github.com/kubernetes/kops/releases/download/${KOPS_CLI_VERSION}/kops-${TARGETOS}-${TARGETARCH}" "${WORKSPACE_ROOT_DIR}/"

# install kubectl
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/kops-${TARGETOS}-${TARGETARCH}" "/usr/local/bin/kops"


# container as builder for preparing OTC cloud tools
FROM otc-tools-builder AS otc-tools-kubectl-builder

LABEL stage="otc-tools-kubectl-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool kubectl CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool kubectl CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH
ARG KUBECTL_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download kubectl CLI binary file
ADD "https://dl.k8s.io/release/${KUBECTL_CLI_VERSION}/bin/linux/${TARGETARCH}/kubectl" "${WORKSPACE_ROOT_DIR}/"

# install kubectl
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/kubectl" "/usr/local/bin/"


# container as builder for preparing OTC cloud tools
FROM otc-tools-builder AS otc-tools-kustomize-builder

LABEL stage="otc-tools-kustomize-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool kustomize CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool kustomize CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH
ARG KUSTOMIZE_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download kustomize archive
ADD "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE_CLI_VERSION}/kustomize_v${KUSTOMIZE_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.tar.gz" "${WORKSPACE_ROOT_DIR}/"

# install kustomize
RUN mkdir -p "/usr/local/bin/" && tar -xvf "${WORKSPACE_ROOT_DIR}/kustomize_v${KUSTOMIZE_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.tar.gz" -C "/usr/local/bin" --no-anchored "kustomize"


# container as builder for preparing OTC cloud tools
FROM otc-tools-builder AS otc-tools-opentofu-builder

LABEL stage="otc-tools-opentofu-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool OpenTofu" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool OpenTofu" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH
ARG OPENTOFU_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download OpenTofu CLI archive file
ADD "https://github.com/opentofu/opentofu/releases/download/v${OPENTOFU_CLI_VERSION}/tofu_${OPENTOFU_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.zip" "${WORKSPACE_ROOT_DIR}/"

# install OpenTofu CLI binary
RUN mkdir -p "/usr/local/bin/" && unzip "tofu_${OPENTOFU_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.zip" -d "/usr/local/bin/"


# container as builder for preparing OTC cloud tools
FROM otc-tools-builder AS otc-tools-otc-cli-builder

LABEL stage="otc-tools-otc-cli-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool OTC CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool OTC CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH
ARG OTC_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download OTC CLI binary file (https://github.com/ysoftdevs/otc-cli)
ADD "https://github.com/ysoftdevs/otc-cli/releases/download/${OTC_CLI_VERSION}/otc-${TARGETOS}-${TARGETARCH}" "${WORKSPACE_ROOT_DIR}/otc"

# install OTC CLI
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/otc" "/usr/local/bin/otc"


# container as builder for preparing OTC cloud tools
FROM otc-tools-builder AS otc-tools-swarmcli-builder

LABEL stage="otc-tools-swarmcli-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool SwarmCLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool SwarmCLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH
ARG SWARM_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# install SwarmCLI
RUN mkdir -p "/usr/local/bin/" && \
    curl -fsSL https://swarmcli.io/install.sh | \
    sh -s -- ce /usr/local/bin "${SWARM_CLI_VERSION}"


# container as builder for preparing OTC cloud tools
FROM otc-tools-builder AS otc-tools-terraform-builder

LABEL stage="otc-tools-terraform-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool terraform" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool terraform" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH
ARG TERRAFORM_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download TF CLI archive file
ADD "https://releases.hashicorp.com/terraform/${TERRAFORM_CLI_VERSION}/terraform_${TERRAFORM_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.zip" "${WORKSPACE_ROOT_DIR}/"

# install TF CLI binary
RUN mkdir -p "/usr/local/bin/" && unzip "terraform_${TERRAFORM_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.zip" -d "/usr/local/bin/"


# container as builder for preparing OTC cloud tools
FROM otc-tools-builder AS otc-tools-terragrunt-builder

LABEL stage="otc-tools-terragrunt-builder" \
      description="Alpine-based container builder for preparing OTC cloud tool terragrunt CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OTC cloud tool terragrunt CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH
ARG TERRAGRUNT_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download kubectl CLI binary file
ADD "https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_CLI_VERSION}/terragrunt_${TARGETOS}_${TARGETARCH}" "${WORKSPACE_ROOT_DIR}/"

# install terragrunt CLI
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/terragrunt_${TARGETOS}_${TARGETARCH}" "/usr/local/bin/terragrunt"


FROM scratch AS otc-tools-binaries-aggregator

# transfer tools from builders
COPY --from=otc-tools-ansible-cli-builder "/usr/local/bin" "/usr/local/bin"
COPY --from=otc-tools-ansible-cli-builder "/usr/local/lib/" "/usr/local/lib"
COPY --from=otc-tools-cm-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=otc-tools-cnpg-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=otc-tools-helm-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=otc-tools-k9s-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=otc-tools-kops-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=otc-tools-kubectl-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=otc-tools-kustomize-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=otc-tools-opentofu-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=otc-tools-otc-cli-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=otc-tools-swarmcli-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=otc-tools-terraform-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=otc-tools-terragrunt-builder "/usr/local/bin/" "/usr/local/bin/"


# container as final image for providing OTC cloud tools
FROM dhi.io/alpine-base:${ALPINE_RELEASE} AS otc-tools-image

LABEL stage="otc-tools-image" \
      description="Alpine-based container with OTC cloud tools" \
      org.opencontainers.image.description="Alpine-based container with OTC cloud tools" \
      org.opencontainers.image.url=https://github.com/stefanbosak/otc-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/otc-tools

ARG TARGETOS
ARG TARGETARCH

# user in container
ARG CONTAINER_USER
ARG CONTAINER_GROUP

ARG CONTAINER_USER_ID
ARG CONTAINER_GROUP_ID

ARG HOME_ROOT_DIR="/home/${CONTAINER_USER}"

WORKDIR "${HOME_ROOT_DIR}"

# shadow provides useradd/usermod/groupadd/groupmod with the same flags used below;
# python3 has no "python" alias package on Alpine (unlike Debian's python-is-python3), so it is symlinked explicitly
RUN mkdir -p "/usr/local/bin/" && \
    apk add --no-cache \
      bash \
      bash-completion \
      bc \
      bind-tools \
      ca-certificates \
      curl \
      git \
      gnupg \
      gzip \
      iproute2 \
      iputils \
      jq \
      kmod \
      lsof \
      openssh-client \
      pigz \
      procps \
      psmisc \
      py3-argcomplete \
      python3 \
      ripgrep \
      rsync \
      shadow \
      socat \
      unzip \
      wget \
      whois \
    && ln -sf /usr/bin/python3 /usr/bin/python

# install DiD (Docker in Docker)
# - Alpine ships prebuilt docker/docker-cli packages in its own repos, unlike get.docker.com's
#   convenience script which only targets glibc distros, so apk is used directly here
# - DinD via QEMU on ARM64 is not supported
#   (ARM64 requires ARM64 kernel from host system which is not present on AMD64 host)
RUN apk add --no-cache docker docker-cli && \
    if ! getent group docker > /dev/null 2>&1; then \
      groupadd docker; \
    fi

# copy tools from aggregator
COPY --from=otc-tools-binaries-aggregator / /

# setup user and group
RUN if getent group "${CONTAINER_GROUP_ID}" > /dev/null; then \
      _existing_group="$(getent group "${CONTAINER_GROUP_ID}" | cut -d: -f1)"; \
      if [ "${_existing_group}" != "${CONTAINER_GROUP}" ]; then \
        groupmod -n "${CONTAINER_GROUP}" "${_existing_group}"; \
      fi; \
    else \
      groupadd --gid "${CONTAINER_GROUP_ID}" "${CONTAINER_GROUP}"; \
    fi \
    && if getent passwd "${CONTAINER_USER_ID}" > /dev/null; then \
         _existing_user="$(getent passwd "${CONTAINER_USER_ID}" | cut -d: -f1)"; \
         if [ "${_existing_user}" != "${CONTAINER_USER}" ]; then \
           if [ -d "/home/${_existing_user}" ]; then \
             mv "/home/${_existing_user}" "/home/${CONTAINER_USER}"; \
           fi; \
           usermod -d "${HOME_ROOT_DIR}" -l "${CONTAINER_USER}" "${_existing_user}"; \
         fi; \
       else \
         useradd \
           --uid "${CONTAINER_USER_ID}" \
           --gid "${CONTAINER_GROUP_ID}" \
           --groups "${CONTAINER_GROUP}" \
           -M -d "${HOME_ROOT_DIR}" \
           -s /bin/bash \
           "${CONTAINER_USER}"; \
       fi \
    && chown -R "${CONTAINER_USER}:${CONTAINER_GROUP}" "${HOME_ROOT_DIR}" \
    && usermod -aG docker "${CONTAINER_USER}" && \
# enable tools completions (required to run given tool to generate completion file content)
    ln -s /usr/local/bin/kubectl-cert_manager /usr/local/bin/cmctl && \
    cmctl completion bash > /usr/share/bash-completion/completions/cmctl && \
    ln -s /usr/local/bin/kubectl-cnpg /usr/local/bin/cnpgctl && \
    cnpgctl completion bash > /usr/share/bash-completion/completions/cnpgctl && \
    sed -i 's/kubectl-cnpg/cnpgctl/g' /usr/share/bash-completion/completions/cnpgctl && \
    helm completion bash > "/usr/share/bash-completion/completions/helm" && \
    k9s completion bash > "/usr/share/bash-completion/completions/k9s" && \
    kops completion bash > "/usr/share/bash-completion/completions/kops" && \
    kubectl completion bash > "/usr/share/bash-completion/completions/kubectl" && \
    cp "/usr/share/bash-completion/completions/kubectl" "/usr/share/bash-completion/completions/k" && \
    sed -i 's/kubectl/k/g' "/usr/share/bash-completion/completions/k" && \
    ln -s /usr/local/bin/kubectl /usr/local/bin/k && \
    kustomize completion bash > "/usr/share/bash-completion/completions/kustomize" && \
    echo "complete -C tofu tofu" > "/usr/share/bash-completion/completions/tofu" && \
    otc completion bash > "/usr/share/bash-completion/completions/otc" && \
    echo "complete -C terraform terraform" > "/usr/share/bash-completion/completions/terraform" && \
    echo "complete -C terragrunt terragrunt" > "/usr/share/bash-completion/completions/terragrunt" && \
    activate-global-python-argcomplete

# copy OpenTelekomCloud helper scripts into user profile inside container image
COPY ./scripts "${WORKSPACE_ROOT_DIR}/scripts"

# container user and group
USER "${CONTAINER_USER}:${CONTAINER_GROUP}"

WORKDIR "${HOME_ROOT_DIR}"

# Alpine's /etc/skel only guarantees .profile; .bashrc is copied only if the bash package placed one there
RUN cp /etc/skel/.profile "${HOME_ROOT_DIR}" && \
    if [ -f /etc/skel/.bashrc ]; then cp /etc/skel/.bashrc "${HOME_ROOT_DIR}"; fi

# open shell
CMD ["bash"]
