apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-obs
  namespace: sample-workload
  annotations:
    csi.storage.k8s.io/fstype: obsfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-obs
  resources:
    requests:
      storage: 1Gi
