apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-disk
  namespace: sample-workload
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-disk-ssd
  resources:
    requests:
      storage: 10Gi
